account/urls.py
from django.urls import path
from . import views


app_name = 'account'

urlpatterns = [
    path('login', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('signup', views.user_register, name='signup'),
    # path('edit/', views.user_edit, name='edit'),
    path('edit/', views.user_edit_model, name='edit'),
]

blog/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('list/', views.article_list, name='article-list'),
    path('detail/<slug:slug>', views.article_detail, name='article-detail'),
    path('category/<str:cat>', views.article_list, name='category-list'),
    path('search/', views.search, name='search'),
    path('like/<int:pk>', views.liked, name='like')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('account/', include('account.urls')),
    path('blog/', include('blog.urls')),
    path('rosetta/', include('rosetta.urls')),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partial/footer.html
{% load static %}
{% load i18n %}
<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <ul class="social-icons">
                    <li><a href="#">{% translate "Facebook" %}</a></li>
                    <li><a href="#">{% translate "Twitter" %}</a></li>
                    <li><a href="#">{% translate "Behance" %}</a></li>
                    <li><a href="#">{% translate "Linkedin" %}</a></li>
                    <li><a href="#">{% translate "Dribbble" %}</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="copyright-text">
                    <p>
                        {% translate "Copyright 2020 Stand Blog Co. | Design:" %}
                        <a rel="nofollow" href="https://templatemo.com" target="_parent">TemplateMo</a>
                    </p>
                </div>
            </div>
        </div>
    </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

<!-- Additional Scripts -->
<script src="{% static 'js/custom.js' %}"></script>
<script src="{% static 'js/owl.js' %}"></script>
<script src="{% static 'js/slick.js' %}"></script>
<script src="{% static 'js/isotope.js' %}"></script>
<script src="{% static 'js/accordions.js' %}"></script>

<script language="text/Javascript">
    cleared[0] = cleared[1] = cleared[2] = 0; //set a cleared flag for each field
    function clearField(t) {
        //declaring the array outside of the
        if (!cleared[t.id]) {
            // function makes it static and global
            cleared[t.id] = 1; // you could use true and false, but that's more typing
            t.value = ""; // with more chance of typos
            t.style.color = "#fff";
        }
    }
</script>

templates/partial/head.html
{% load static %}
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="TemplateMo" />
    <link
        href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i&display=swap"
        rel="stylesheet" />

    <title> {% block title %}Stand CSS Blog by TemplateMo{% endblock title %} </title>

    <!-- Bootstrap core CSS -->
    <link href=" {% static 'vendor/bootstrap/css/bootstrap.min.css' %} " rel="stylesheet" />

    <!-- Additional CSS Files -->
    <link rel="stylesheet" href=" {% static 'css/fontawesome.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/templatemo-stand-blog.css' %}" />
    <link rel="stylesheet" href=" {% static 'css/owl.css' %}" />
    <!--

    TemplateMo 551 Stand Blog

    https://templatemo.com/tm-551-stand-blog

    -->
</head>

templates/partial/header.html
{% load static %}
{% load i18n %}
{% load l10n %}
    <!-- ***** Preloader Start ***** -->
    <div id="preloader">
        <div class="jumper">
            <div>Hello</div>
            <div></div>
            <div></div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->

    <!-- Header -->
    <header class="">
        <nav class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand" href="{% url 'home' %}">
                    <h2> "Stand Blog" <em>.</em></h2>
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive"
                    aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        
                        <li class="nav-item {% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'home' %}"> {% translate "Home"%}  
                                <span class="sr-only">(current)</span>
                            </a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'article-list' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'article-list' %}">{% translate "All Articles" %}</a>
                        </li>
                        <li class="nav-item {% if request.resolver_match.url_name == 'about-us' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'about' %}">{% translate "About Us" %}</a>
                        </li>

                        {% comment %} <li class="nav-item">
                            <a class="nav-link" href="post-details.html">Post Details</a>
                        </li> {% endcomment %}
                        <li class="nav-item {% if request.resolver_match.url_name == 'contact-us' %}active{% endif %}">
                            <a class="nav-link" href="{% url 'contact' %}">{% translate "Contact Us" %}</a>
                        </li>
                        <li class="nav-item">
                            
                            {% if request.user.is_authenticated %}
                            <li class="nav-item mt-1">
                                {% if user.profile.image%}
                                <img src="{{user.profile.image.url}}" width="30px" height="30px" style="border-radius: 100%;" alt="">
                                {% else %}
                                <img src="{% static 'images/icons/profile.jpg' %}" width="30px" height="30px" style="border-radius: 100%;" alt="">
                                {% endif %}
                            </li>
                            <a class="nav-link" href="#"> {{request.user.username}} </a>
                            <li class="nav-item">
                                <a class="nav-link badge badge-danger mt-2" href="{% url 'account:logout' %}"> {% trans "Log Out" %} </a>
                            </li>
                            {% else %}
                            <a class="nav-link" href=" {% url 'account:login' %}"> {% trans "Login" %} </a>  
                            <li class="nav-item">
                                <a class="nav-link" href=" {% url 'account:signup' %}"> {% trans "Sign Up" %} </a>
                            </li>
                            {% endif %}
                                

                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
 

templates/partial/side_bar.html
<div class="col-lg-4">
  <div class="sidebar">
    <div class="row">
      <div class="col-lg-12">
        <div class="sidebar-item search">
          <form id="search_form" name="gs" method="GET" action="{% url 'search' %}">
            <input
              type="text"
              name="q"
              id="search"
              class="searchText"
              {% if request.GET.q %}value="{{request.GET.q}}"{% endif %}
              placeholder="type to search..."
              autocomplete="on" 
            />
          </form>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="sidebar-item recent-posts">
          <div class="sidebar-heading">
            <h2>Recent Posts</h2>
          </div>
          <div class="content">
            <ul>
              {% for rec in recent %}
              <li>
                <a href="post-details.html">
                  <h5>{{rec.title}}</h5>
                  <span>{{rec.created_date}}</span>
                </a>
              </li>
              {% endfor %}

              {% comment %} <li>
                <a href="post-details.html">
                  <h5>
                    Suspendisse et metus nec libero ultrices varius eget in
                    risus
                  </h5>
                  <span>May 28, 2020</span>
                </a>
              </li>
              <li>
                <a href="post-details.html">
                  <h5>
                    Swag hella echo park leggings, shaman cornhole ethical
                    coloring
                  </h5>
                  <span>May 14, 2020</span>
                </a>
              </li> {% endcomment %}
            </ul>
          </div>
        </div>
      </div>

      <div class="col-lg-12">
        <div class="sidebar-item categories">
          <div class="sidebar-heading">
            <h2>Categories</h2>
          </div>
          <div class="content">
            <ul>
              {% for cat in categories %}
              <li><a href="{% url 'category-list' cat.name %}">- {{cat.name}} </a></li>
              {% endfor %}
              {% comment %} <li><a href="#">- Awesome Layouts</a></li>
              <li><a href="#">- Creative Ideas</a></li>
              <li><a href="#">- Responsive Templates</a></li>
              <li><a href="#">- HTML5 / CSS3 Templates</a></li>
              <li><a href="#">- Creative &amp; Unique</a></li> {% endcomment %}
            </ul>
          </div>
        </div>
      </div>
      <div class="col-lg-12">
        <div class="sidebar-item tags">
          <div class="sidebar-heading">
            <h2>Tag Clouds</h2>
          </div>
          <div class="content">
            <ul>
              <li><a href="#">Lifestyle</a></li>
              <li><a href="#">Creative</a></li>
              <li><a href="#">HTML5</a></li>
              <li><a href="#">Inspiration</a></li>
              <li><a href="#">Motivation</a></li>
              <li><a href="#">PSD</a></li>
              <li><a href="#">Responsive</a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>